FROM node:22.14.0-alpine

RUN apk add --no-cache docker-cli

WORKDIR /opt/supabase-cli
RUN npm init -y \
  && npm install --save-exact supabase@2.109.1

ENTRYPOINT ["/opt/supabase-cli/node_modules/.bin/supabase"]
